spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?characterEncoding=UTF-8
    username: kdt
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialet: org.hibernate.dialect.MySQL5InnoDBDialect